---
# tasks file for k8s
- block:
  - name: Initialize Kubernetes Master with kubeadm init
    command: kubeadm init --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address={{ ansible_host }} #{{ kubernetes_apiserver_advertise_address | default(ansible_default_ipv4.address, true) }} 
    register: kubeadm_initialize
    run_once: true
    with_items:
    - "{{ groups['masters'][0] }}"
 
  - name: Ensure .kube directory exists.
    file:
      path: ~/.kube
      state: directory

  - name: Symlink the kubectl admin.conf to ~/.kube/conf.
    file:
      src: /etc/kubernetes/admin.conf
      dest: ~/.kube/config
      state: link

  - name: 'Use Calico Plugin to get the config in yaml. And this should be run only on Master node'
    command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  become: true
